<!-- 
This file by Martin Monkman 
is licensed under a Creative Commons Attribution 4.0 International License
https://creativecommons.org/licenses/by/4.0/  
-->


# Gapminder:  200 Countries, 200 Years {#gapminder200}


```{r echo = FALSE}
library(knitr)
opts_chunk$set(message = FALSE, warning = FALSE, cache = TRUE)
options(width = 100, dplyr.width = 100)

```

## Introduction {#gapminder200-intro}


In this project, you will recreate  single year versions of the chart Hans Rosling shows in the videos here:

* Gapminder, [200 Countries, 200 Years, 4 Minutes](https://www.gapminder.org/videos/200-years-that-changed-the-world-bbc/)

* Gapminder, [Hans Rosling: 200 years in 4 minutes - BBC News](https://www.youtube.com/watch?v=Z8t4k0Q8e8Y)

The plots in both have the same information shown: income, life expectancy, population, and the continent.

## Data files {#gapminder200-data}

The four files that you will need, downloaded from https://www.gapminder.org/data/, can be found in the "data" folder of this project.

There are CSV files for the following:

* Income: "income_per_person_gdppercapita_ppp_inflation_adjusted.csv"

* Life expectancy (years): "life_expectancy_years.csv"

* Population: "population_total.csv"

In addition, there is an Excel file that you'll need to use to get the region (continent) that each country is in. Use the variable "four_regions" for the continents.

* "Data Geographies - v1 - by Gapminder.xlsx", sheet = "list-of-countries-etc"






## References {#gapminder200-ref}

### Animation of plots 

Part of what makes Hans Rosling's presentations so compelling is the animation of the data visualization. Here are some links to resources for you to create an animated plot in R, using the package {gganimate}. 

* [{gganimate} package reference page](https://gganimate.com/index.html) -- note that the "Getting Started" page has a good guide to the basics of the package

* [{gganimate} cheat sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/gganimate.pdf)

* [GGANIMATE: HOW TO CREATE PLOTS WITH BEAUTIFUL ANIMATION IN R](https://www.datanovia.com/en/blog/gganimate-how-to-create-plots-with-beautiful-animation-in-r/) -- includes some more advanced methods

* Tristan Ganry, [How to build Animated Charts like Hans Rosling — doing it all in R](https://towardsdatascience.com/how-to-build-animated-charts-like-hans-rosling-doing-it-all-in-r-570efc6ba382) (2018-05-19)



-30-


