<!-- 
This file by Martin Monkman 
is licensed under a Creative Commons Attribution 4.0 International License
https://creativecommons.org/licenses/by/4.0/  
-->


# Bat Echolocation {#bat-echolocation}


## Introduction {#bat-echolocation-intro}

Echolocation call data for 4 species of Vancouver Island bats (https://www.bcbats.ca/index.php/bat-basics/bc-bat-species). Call data comprises 30 unique records for 4 echolocation call parameters for each of the bat species. Call data was recorded using an ultrasonic bat detector (Anabat; Titley Scientific https://www.titley-scientific.com/) with call parameters downloaded and extracted using AnaLook.

For this project, explore the data using the inspiration provided by the penguin analysis (below).


### Data source {#bat-echolocation-data}

Variables:

**Species**

EPFU - Eptesicus fuscus; Big Brown Bat

LACI - Lasiurus cinereus; Hoary Bat

MYLU - Myotis lucifugus; Little Brown Bat

MYVO - Myotis volans; Long-legged Myotis

**Filename** - Unique ID for each bat call

_**Echolocation Call Paramters:**_

**Time_Btw_Calls** - Time between calls (milliseconds)

**Duration** - Duration of the body of call (milliseconds)

**Frequency** - Characteristic frequency (kHz)

**Slope** - Characteristic slope


Source: Dr. Joanna Burgar; https://github.com/joburgar/Bat_Data 


### Additional Inspiration {#bat-echolocation-palmerpenguins}

The R package {palmerpenguins} reference page has some tabulations and visualizations that may provide some inspiration:

* https://allisonhorst.github.io/palmerpenguins/

* in particular, the "Get started" and "Articles" have both the visualizations and the code used to create those visualizations.




## Other resources {#bat-echolocation-other}

**Statistical analysis of bat calls**

David W. Armitage and Holly K. Ober, [A comparison of supervised learning techniques in the classification of bat echolocation calls](https://static1.squarespace.com/static/55a69002e4b0a72683b3d92f/t/59b6e72cc027d84ada362604/1505158956736/Armitage+%26+Ober+2010.pdf), _Ecological Infomatics_, 2010, 5, 465:473.


Xing Chen, Jun Zhaob, Yan-hua Chen, Wei Zhoub, and Alice C.Hughes, [Automatic standardized processing and identification of tropical bat calls using deep learning approaches](https://www.sciencedirect.com/science/article/pii/S0006320719308961), _Biological Conservation_, January 2020, Vol.241, doi: 10.1016/j.biocon.2019.108269


Oisin MacAodha, Rory Gibb, Kate E. Barlow, et al., [Bat detective—Deep learning tools for bat acoustic signal detection](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005995), _PLOS Computational Biology_, 2018-03-08, doi: 10.1371/journal.pcbi.1005995 


Keisuke Masuda, Takanori Matsui, Dai Fukui, et al., [Bat species classification by echolocation call using a machine learning system](https://www.jstage.jst.go.jp/article/mammalianscience/57/1/57_19/_article), _Honyurui Kagaku (Mammalian Science)_, Volume 57 (2017) Issue 1. doi: 10.11238/mammalianscience.57.19


Peter Ommundsen,Cori Lausen, Laura Matthias, [First Acoustic Records of the Brazilian Free-Tailed Bat (Tadarida brasiliensis) In British Columbia](https://www.researchgate.net/publication/319424456_First_Acoustic_Records_of_the_Brazilian_Free-Tailed_Bat_Tadarida_brasiliensis_In_British_Columbia), September 2017, _Northwestern Naturalist_, 98(2):132-136, DOI: 10.1898/NWN16-24.1



Veronica Zamora-Gutierrez, Celia Lopez-Gonzalez, M. Cristina MacSwiney Gonzalez, et al., [Acoustic identification of Mexican bats based on taxonomic and ecological constraints on call design](https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1111/2041-210X.12556), _Methods in Ecology and Evolution_ 2016, 7, 1082–1091. doi: 10.1111/2041-210X.12556


**Other bat communication**

Jason Daley, [Researchers “Translate” Bat Talk. Turns Out, They Argue—A Lot](https://getpocket.com/explore/item/researchers-translate-bat-talk-turns-out-they-argue-a-lot), _Smithsonian Magazine_, 2016-12-22.



-30-
