---
title: 'BIDA302: Lesson Plan, Week 1'
author: "Martin Monkman"
date: 'latest revision: `r Sys.Date()`'
output:
  html_document: default
  word_document: default
subtitle: 2020-10-24 & 2020-10-25
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***

**_subject to change_**



## Objectives

> The important thing is that you solve the problem that you’re working on, not write the most concise and elegant code (although that’s definitely something you want to strive towards!)
> - Grolemund & Wickham, _R for Data Science_


At the end of this lesson, learners will be able to:

1. Describe the fundamental elements of data manipulation, and 

2. Demonstrate how these can be applied using R.


***

## Activities

| Block      | Time           | Topics  | &#8212; |
|---         |:---            |:---     |:---:  |
|**Saturday**     | &#8212;  | &#8212; | &#8212; |
|1a          | 9:00 to 9:30   | Welcome to BIDA302!  | &#8212; |
|1b <br> 1c  | 9:30 to 10:30  | Why code? Why R? <br> Introduction to R and RStudio | &#8212; |
|&#8212:     | 10:30 to 10:45 | _break_ | &#8212; |
|2a <br> 2b  | 10:45 to 12:00 | The data science process <br> Programming foundations | &#8212; |
|**Sunday**     | &#8212;  | &#8212; | &#8212; |
|3           | 9:00 to 9:30   | The data science process (walk-through) <br> Data wrangling (continued) | &#8212; |
|&#8212;     | 10:30 to 10:45   | _break_ | &#8212; |
|4a          | 9:30 to 10:30   | Assignment 1 | &#8212; |
|4b <br> 4c  | 10:45 to 12:00   | Installing R on your own computer <br> Wrap up | &#8212; |


***

## Saturday (2020-10-24)


### 1a. Welcome!

Format: participation and instructor lecture w/ slides

Time allocation: 30 minutes (9:00 to 9:30)


#### Welcome!

* Introducing the instructor

* Value of community 

* Icebreaker

  - Learning a new language
  
  - Data analysis experience
  
  - Coding experience


#### What to expect in this class

* read the syllabus!

* course flow

* assignments and evaluation

* Moodle

### 1b. Why Code? Why R?

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (9:30 to 9:45)


### 1c. An introduction to R, RStudio Cloud, and R Markdown

Format: learner (instructor guided), using RStudio Cloud

Time allocation: 45 minutes (9:45 to 10:30)



## BREAK

Time allocation: 15 minutes (10:30 to 10:45)

***

### 2a. The Data Science Process

Format: instructor, lecture w/slides

Time allocation: 15 minutes (10:45 to 11:00)


### 2b. Programming foundations

Format: instructor, lecture w/slides

Time allocation: 15 minutes (10:45 to 11:00)



Format: learner (instructor guided)

Time allocation: 60 minutes (11:00 to 12:00)


### Take-home exercise:

[Introduction to R](https://monkmanmh.shinyapps.io/BIDA302_1-1_intro/?_ga=2.143188981.1105120215.1603418925-1358848496.1603418925)



## Reading ahead...

* [_R for Data Science_, Workflow: basics](https://r4ds.had.co.nz/workflow-basics.html)

* [_R for Data Science_, Data Transformation](https://r4ds.had.co.nz/transform.html)



***

## Sunday (2020-10-25)


### 3a. The Data Science Process -- example walkthrough

Format: instructor, lecture w/slides

Time allocation: 30 minutes (9:00 to 9:30)


### 3b. Data Wrangling 

Format: instructor, lecture w/slides

Time allocation: 15 minutes (9:30 to 9:45)


Format: learner (instructor guided)

Time allocation: 45 minutes (9:45 to 10:30)


***

## BREAK

Time allocation: 15 minutes (2:45 to 3:00)


***

## 4a. Assignment #1

Time allocation: 30 minutes (3:00 to 3:30)


## 4b. Wrap up

Time allocation: 30 minutes (3:30 to 4:00)

### Summary

Format: instructor summary, w/ slides

### Questions?

Format: learner Q&A

### Preview/readings for next lesson

Format: instructor summary, w/ slides




***

## Readings & Reference Materials

### Installing R on your own computer

[_R Cookbook, 2nd ed._](https://rc2e.com/gettingstarted#recipe-id001)

* 1.1 Downloading and Installing R

* 1.2 Installing RStudio

* 1.3 Starting RStudio


### Packages

#### R Markdown

[R Markdown reference at RStudio](https://rmarkdown.rstudio.com/docs/)

[R Markdown cheat sheet](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf) (PDF file)


#### {dplyr} .

[{dplyr} reference at tidyverse.org](https://dplyr.tidyverse.org/)

[Data Transformation Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf) (PDF file)


#### {tidyr} .

[{tidyr} reference at tidyverse.org](https://tidyr.tidyverse.org/)





### Readings from _R4DS_

Garrett Grolemund and Hadley Wickham, [R for Data Science](https://r4ds.had.co.nz/)

* [4. Workflow: basics](https://r4ds.had.co.nz/workflow-basics.html)

* [5. Data Transformation](https://r4ds.had.co.nz/transform.html)

* [6. Workflow: scripts](https://r4ds.had.co.nz/workflow-scripts.html)

* [27. R Markdown](https://r4ds.had.co.nz/r-markdown.html)

* [12. Tidy data](https://r4ds.had.co.nz/tidy-data.html), sections 12.1 to 12.3


### Other required reading

#### 

The BIDA302 [Course Outline](https://distance.moodle.uvcs.uvic.ca/mod/resource/view.php?id=154351)


#### Naming things

Jenny Bryan, ["How to name files"](https://speakerdeck.com/jennybc/how-to-name-files)

* https://twitter.com/JennyBryan/status/807805087544328192?s=20


#### Tidy data

[Reshaping Your Data with tidyr](https://uc-r.github.io/tidyr), UC Business Analytics R Programming Guide

* this article uses the old {tidyr} `gather()` and `spread()` functions instead of `pivot_longer()` and `pivot_wider()`, but it's got some good material on how to think about how and why data needs to be reshaped.




### Digging deeper into this week's topics


#### Opinionated analysis development / reproducible analysis

Hilary Parker, 2017-08-31, [Opinionated analysis development](https://peerj.com/preprints/3210/), PeerJ Preprints 5:e3210v1 https://doi.org/10.7287/peerj.preprints.3210v1

[The reproducible workflow](https://remi-daigle.github.io/2017-CHONe-Data/cleaning.nb.html) -- from Data Management Workshop à la CHONe

Munafò, M., Nosek, B., Bishop, D. et al. [A manifesto for reproducible science](https://www.nature.com/articles/s41562-016-0021). Nat Hum Behav 1, 0021 (2017) doi:10.1038/s41562-016-0021


#### Why R?

Nathaniel D. Phillips, [YaRrr! The Pirate’s Guide to R](https://bookdown.org/ndphillips/YaRrr/) 

- [Chapter 1.3, "Why is R so great?"](https://bookdown.org/ndphillips/YaRrr/why-is-r-so-great.html)

- [Chapter 2, "Getting Started"](https://bookdown.org/ndphillips/YaRrr/started.html) provides a good summary of R, RStudio, and packages

"History and Overview of R", Chapter 2 in Roger Peng, 2019-12-22, [_R Programming for Data Science_](https://bookdown.org/rdpeng/rprogdatascience/history-and-overview-of-r.html)

Lucy D'Agostino McGowan, 2017-07-28, [R release names](https://livefreeordichotomize.com/2017/09/28/r-release-names/)

- [an up-to-date list](https://bookdown.org/martin_monkman/DataScienceResources_book/using-r.html#r-release-names)



#### R Markdown

[Introduction to literate programming in R](https://remi-daigle.github.io/2017-CHONe-Data/Rmarkdown.nb.html) -- from Data Management Workshop à la CHONe




### Getting ready for next week


#### Readings from _R4DS_

Garrett Grolemund and Hadley Wickham, [R for Data Science](https://r4ds.had.co.nz/)

* [5. Data Transformation](https://r4ds.had.co.nz/transform.html) -- 5.2.3, Missing Values

* [11. Data import](https://r4ds.had.co.nz/data-import.html)



#### Tidy data

Julia Lowndes and Allison Horst, [Tidy data for efficiency, reproducibility, and collaboration](https://www.openscapes.org/blog/2020/10/12/tidy-data/)

* in google slide version: ["Make friends with tidy data"](https://docs.google.com/presentation/d/1N7hKepabvl9OrHjvGJWPjUsfzVdB5xzV5AsFndgSwms/edit#slide=id.p)

Hadley Wickham. ["Tidy data"](https://vita.had.co.nz/papers/tidy-data.html), _The Journal of Statistical Software_, vol. 59, 2014.

Karl Broman and Kara Woo, ["Data organization in spreadsheets"](https://doi.org/10.1080/00031305.2017.1375989), _The American Statistician_ 72 (1): 2–10.

[Data Organization in Spreadsheets for Social Scientists: Formatting problems](https://datacarpentry.org/spreadsheets-socialsci/02-common-mistakes/index.html) -- DataCarpentry lesson

[Data organization with spreadsheets](https://remi-daigle.github.io/2017-CHONe-Data/organization.nb.html) -- from Data Management Workshop à la CHONe


#### Thinking about your capstone project

Gapminder data -- Hans Rosling

* [The best stats you've ever seen](https://www.ted.com/talks/hans_rosling_the_best_stats_you_ve_ever_seen?language=en) -- this is the video we watched in class

* [200 Countries, 200 Years, 4 Minutes](https://www.gapminder.org/videos/200-years-that-changed-the-world-bbc/) -- recreating the chart in this video is one of the capstone project options


Stephanie Hazlitt's fence, 2019-02-10 - [Weather with weathercan 🇨🇦](https://github.com/stephhazlitt/some-assembly-required/blob/master/R/fence/fence.md)

* https://twitter.com/stephhazlitt/status/1099904166124605441?s=20

* https://twitter.com/stephhazlitt/status/1101721399243112449?s=20



### Approaching data analysis

_R4DS_

* [7. Exploratory Data Analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html) -- While this chapter has "how-to" information, it also contains a structured way to approach the analysis:

> 1. Generate questions about your data.
>
> 2. Search for answers by visualising, transforming, and modelling your data.
>
> 3. Use what you learn to refine your questions and/or generate new questions.


Cole Nussbaumer Knaflic, [_Storytelling with Data: A Data Visualization Guide for Business Professionals_](http://www.storytellingwithdata.com/books) (2015, Wiley)--this book is focussed on data visualization, but "the data visualization is always in the service of making a point about what the data tell us. In the context of business, this then translates into influencing decisions. The chapter “Lessons in storytelling” falls almost exactly in the middle of the book; after we’ve been introduced to the principles of making good data visualizations, Nussbaumer Knaflic gives us a way to think about the purpose of the visualization. With all of the pieces in place, the remainder of the book is focussed on the applications of storytelling with data."





-30-
