---
title: "BIDA302: Lesson Plan, Week 2"
subtitle: "2020-03-07"
author: "Martin Monkman"
date: "`r Sys.Date()`"
output: html_document
#description: "The syllabus for Data Analytics Coding Fundamentals, UVic BIDA302"
---

# Week 2 (2019-11-09)


| Week      | Date | Topics   | Lesson |
|---        |:---  |:---      |:---:  |
|2          | 2019-11-09 | Good coding habits <br> Tidy data <br> Data wrangling: the basics <br> R Markdown: the next level | &#8212; |


>The data may not contain the answer. The combination of some data and an aching desire for an answer does not ensure that a reasonable >answer can be extracted from a given body of data.
>
>- John Tukey



At the end of this lesson, learners will be able to:

1. Describe the fundamental elements of data manipulation, and 

2. Demonstrate how these can be applied in a data analytics context.


***

## Activities

| Block      | Time           | Topics  | &#8212; |
|---         |:---            |:---     |:---:  |
|1a          | 9:00 to 9:30   | Review Homework #1  | &#8212; |
|1b          | 9:30 to 10:00  | Variable types (including NA) <br> R in data analysis - example  | &#8212; |
|&#8212:     | 10:00 to 10:15 | _break_ | &#8212; |
|2a          | 10:15 to 12:00 | Tidy data <br> running R Markdown | &#8212; |
|2b          | &#8212;        | Importing data | &#8212; |
|&#8212;     | 12:00 to 1:00  | _lunch_ | &#8212; |
|3           | 1:00 to 2:15   | Importing data (continued) | &#8212; |
|&#8212;     | 2:15 to 2:30   | _break_ | &#8212; |
|4a          | 2:30 to 3:00   | Assignment 2 | &#8212; |
|4b <br> 4c  | 3:00 to 4:00   | Questions? Comments? <br> Wrap up | &#8212; |



### 1a. Review Homework #1

* including submissions via moodle

Format: participation and instructor lecture w/ slides

Time allocation: 30 minutes (9:00 to 9:45)


### 1b. Variable types 

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (9:45 to 10:00)





***

## BREAK

Time allocation: 15 minutes (10:00 to 10:15)

***

### 2a. Tidy data & good coding habits

Format: instructor, lecture w/slides

Time allocation: 30 minutes (10:15 to 10:45)


### 2b. Importing data

Format: instructor, lecture w/slides

Time allocation: 15 minutes (10:45 to 11:00)



Format: learner (instructor guided)

Time allocation: 60 minutes (11:00 to 12:00)

***

## LUNCH

Time allocation: 60 minutes (12:00 to 1:00)

***

### 3. Data Wrangling (part 2)

Format: instructor, lecture w/slides

Time allocation: 15 minutes (1:00 to 1:15)


Format: learner (instructor guided)

Time allocation: 60 minutes (1:15 to 2:15)


***

## BREAK

Time allocation: 15 minutes (2:15 to 2:30)


***

## 4a. Assignment #1

Time allocation: 30 minutes (2:30 to 3:00)


## 4b. Installing R & RStudio on your own computer

Time allocation: 15 minutes (3:15 to 3:30)


## 4c. Wrap up

Time allocation: 30 minutes (3:30 to 4:00)

### Summary

Format: instructor summary, w/ slides

### Questions?

Format: learner Q&A

### Preview/readings for next lesson

Format: instructor summary, w/ slides





## Resources

[Reshaping Your Data with tidyr](https://uc-r.github.io/tidyr), UC Business Analytics R Programming Guide

* this article uses the old {tidyr} `gather()` and `spread()` functions, but it's got some good material on how to think about how and why data needs to be reshaped


## COVID19 data


Map: [Coronavirus COVID-19 Global Cases by Johns Hopkins CSSE](https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html?fbclid=IwAR3PMzQMuQe2eif2py8qRSk_dZtOilkX0aphxWAKGlxuO9pyKm3qoa0fU_A#/bda7594740fd40299423467b48e9ecf6)

Dashboard: [Coronavirus data visualization](https://ramikrispin.github.io/coronavirus_dashboard/?fbclid=IwAR04ENIjfmU-I9xId2m_g1x_sZLN9ZlewrPRTWN0S91_QmtRJi4steG1kaU#summary) -- built using R

Data tables: [COVID-19 Coronavirus Outbreak](https://www.worldometers.info/coronavirus/) from worldometers.info



-30-