---
title: "BIDA302: Lesson Plan, Week 3"
subtitle: ""
author: "Martin Monkman"
date: "`r Sys.Date()`"
output: html_document
#description: "The syllabus for Data Analytics Coding Fundamentals, UVic BIDA302"
---

# Week 3 (2020-11-07 and 2020-11-08)



> Graphs and charts let you explore and learn about the structure of the information you collect. Good data visualizations also make it easier to communicate your ideas and findings to other people.
> - Kieran Healy, _Data Visualization: A Practical Introduction_ (2019)


At the end of this lesson, learners will be able to:

1. Describe the fundamental elements of data visualization in a data analytics context, 

2. Manipulate data by joining two or more data tables, and 

2. Demonstrate how these can be applied using R.


***

## Activities

_(subject to change)_

| Block      | Time           | Topics  | &#8212; |
|---         |:---            |:---     |:---:  |
|**Saturday**     | &#8212;  | &#8212; | &#8212; |
|1a          | 9:00 to 9:30   | Review Homework #2  | &#8212; |
|1b          | 9:30 to 10:30  | Introduction to data visualization  | &#8212; |
|&#8212:     | 10:30 to 10:45 | _break_ | &#8212; |
|2a          | 10:45 to 12:00 | Working with categorical variables | &#8212; |
|2b          | &#8212;        | Exploratory data analysis with visualization | &#8212; |
|**Sunday**     | &#8212;  | &#8212; | &#8212; |
|3           | 1:00 to 2:15   | Relational data | &#8212; |
|&#8212;     | 2:15 to 2:30   | _break_ | &#8212; |
|4a          | 2:30 to 3:00   | Assignment 3 <br> Project| &#8212; |
|4b <br> 4c  | 3:00 to 4:00   | Questions? Comments? <br> Wrap up | &#8212; |



## Saturday 2020-11-08


### 1a. Review Homework #2

* including submissions via moodle

Format: participation and instructor lecture w/ slides

Time allocation: 30 minutes (9:00 to 9:30)


### 1b. Introduction to data visualization with {ggplot2}

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (9:30 to 9:45)

Format: hands-on exercise

Time allocation: 45 minutes (9:45 to 10:30)

_Reading:_

* _R4DS_, ["Data visualisation"](https://r4ds.had.co.nz/data-visualisation.html)

* _R4DS_, ["Exploratory Data Analysis"](https://r4ds.had.co.nz/exploratory-data-analysis.html)

***

## BREAK

Time allocation: 15 minutes (10:30 to 10:45)

***


### 2a. Working with categorical variables - {forcats}

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (10:45 to 11:00)

_Reading:_

* _R4DS_, ["Factors"](https://r4ds.had.co.nz/factors.html)


### 2b. Exploratory data analysis with visualization

* including plotting with categorical variables

Format: hands-on exercise

Time allocation: 60 minutes (11:00 to 12:00)



***

## Sunday 2020-11-09


### 3. Relational data with {dplyr}

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (1:00 to 1:15)

Format: hands-on exercise

Time allocation: 60 minutes (1:15 to 2:15)

_Reading:_

* _R4DS_, ["Relational data"](https://r4ds.had.co.nz/relational-data.html)


***

## BREAK

Time allocation: 15 minutes (2:15 to 2:30)


***



### 4a. Assignment #3 and The Project

Format: participation and instructor lecture w/ slides

Time allocation: 30 minutes (2:30 to 3:30)



### 4b. Wrap up

Time allocation: 30 minutes (3:30 to 4:00)

#### Summary

Format: instructor summary, w/ slides

#### Questions?

Format: learner Q&A

#### Preview/readings for next lesson

Format: instructor summary, w/ slides


---


## Exercises


[BIDA302: Plotting with {ggplot2}](https://monkmanmh.shinyapps.io/BIDA302_3_2_plot/#section-plotting-with-ggplot2)

* an introduction to plotting

[BIDA302: Factors and Plotting](https://monkmanmh.shinyapps.io/BIDA_3_3_factor_plot/#section-factors)

* further examples of plotting, with an introduction to factor variables





## Readings & Reference Materials



### Readings from _R4DS_

Garrett Grolemund and Hadley Wickham, [R for Data Science](https://r4ds.had.co.nz/)

* [3. Data visualisation](https://r4ds.had.co.nz/data-visualisation.html)

* [15. Factors](https://r4ds.had.co.nz/factors.html)

* [13. Relational data](https://r4ds.had.co.nz/relational-data.html)

### Packages

#### {ggplot2} .

[{ggplot2} reference at tidyverse.org](https://ggplot2.tidyverse.org/)

David Smith, [The Financial Times and BBC use R for publication graphics](https://blog.revolutionanalytics.com/2018/06/ft-bbc-uses-r.html) - _Revolutions_, 2018/06-27

[Why The Urban Institute Visualizes Data with ggplot2](https://medium.com/@urban_institute/why-the-urban-institute-visualizes-data-with-ggplot2-46d8cfc7ee67), 2018-05-01


#### {dplyr} .

[{dplyr}: two-table verbs](https://dplyr.tidyverse.org/articles/two-table.html)




-30-
