---
title: "BIDA302: Lesson Plan, Week 4"
subtitle: "2020-03-21"
author: "Martin Monkman"
date: "`r Sys.Date()`"
output: html_document
#description: "The syllabus for Data Analytics Coding Fundamentals, UVic BIDA302"
---

# Week 4 


## Objective

At the end of this lesson, learners will be able to:

1. Describe the different join types, and 

2. Demonstrate how joins are applied in a data analytics context.

3. Demonstrate their ability to write a simple function in R.

4. Have a foundational understanding of modeling in R.



***

## Activities

_(subject to change)_

| Hour  | Block      | Time              | Topics  | &#8212; |
|---    |:---        |:---               |:---:  |
|**1**  |            | **9:00 to 10:00** |    |   |
|       |1a          | 9:00 to 9:20      | Moving online: Blackboard Collaborative | &#8212; |
|       |1c          | 9:20 to 9:30      | Revised course evaluation | &#8212; |
|       |1c          | 9:30 to 10:00     | Course: mid-point review | &#8212; |
|**2**  |            | **10:00 to 11:00**| &#8212;  | &#8212; |
|       |&#8212;     | 10:00 to 10:15    | _break_ | &#8212; |
|       |2a          | 10:15 to 11:00    | Review Homework Exercise #3  <BR> * Data import and plotting | &#8212; |
|**3**  |            | **11:00 to 12:00**| &#8212;  | &#8212; |
|       |&#8212;     | 11:00 to 11:15    | _break_ | &#8212; |
|       |3a          | 11:15 to 12:00    | Review Homework Exercise #3  <BR> Joins (relational data) | &#8212; |
|&#8212;|&#8212;     | 12:00 to 1:00     | _lunch_ | &#8212; |
|**4**  |            | **1:00 to 2:00**  | &#8212;  | &#8212; |
|       |4a          | 1:00 to 2:00      | Writing your own functions | &#8212; |
|**5**  |            | **2:00 to 3:00**  | &#8212;  | &#8212; |
|       |&#8212;     | 2:00 to 2:15      | _break_ | &#8212; |
|       |5a          | 2:15 to 3:00      | Introduction to modeling | &#8212; |
|**6**  |            | **3:00 to 4:00**  | &#8212;  | &#8212; |
|       |&#8212;     | 3:00 to 3:15      | _break_ | &#8212; |
|       |4a          | 3:15 to 3:30      | Capstone Project | &#8212; |
|       |4b          | 3:30 to 3:45      | Assignment 4 | &#8212; |
|       |4c          | 3:45 to 4:00      | Questions? Comments? <br> Wrap up | &#8212; |



### 1a. Moving online: Blackboard Collaborative

Format: instructor demonstration and participation 

Time allocation: 20 minutes (9:00 to 9:20)

Link: https://ca.bbcollab.com/guest/c98a1689208746e988ce36a13be8cb55

* remember to use the Google Chrome browser!

If you want to dial in (perhaps your computer doesn't have good audio) you can call

Call in anonymously. Attendees using this PIN appear as anonymous callers in the session. 
• +1-571-392-7651
• PIN: 7409529098


### 1b. Revised course evaluation

Format: instructor lecture w/ slides 

Time allocation: 10 minutes (9:20 to 9:30)


### 1c. Course: mid-point review

Format: participation and instructor lecture w/ slides


Format: hands-on exercise

Time allocation: 30 minutes (9:30 to 10:00)


***

## BREAK

Time allocation: 15 minutes (10:00 to 10:15)

***


### 2a. Review Homework Exercise #3 - data importing and plotting

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (10:15 to 10:30)

Format: hands-on exercise

Time allocation: 30 minutes (10:30 to 11:00)



***

## BREAK

Time allocation: 15 minutes (11:00 to 11:15)

***


### 3a. Review Homework Exercise #3 - joins (relational data)

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (11:15 to 11:30)

Format: hands-on exercise

Time allocation: 30 minutes (11:30 to 12:00)


***

## LUNCH

Time allocation: 60 minutes (12:00 to 1:00)

***





### 4. Writing your own functions (1)

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (1:00 to 1:15)

_Reading:_

* _R4DS_, ["Functions"](https://r4ds.had.co.nz/functions.html)


Format: hands-on exercise

Time allocation: 45 minutes (1:15 to 2:00)



***

## BREAK

Time allocation: 15 minutes (2:00 to 2:15)

***




### 5. Writing your own functions (2)



Format: hands-on exercise

Time allocation: 45 minutes (2:15 to 3:00)





***

## BREAK

Time allocation: 15 minutes (3:00 to 3:15)


***




### 6a. Capstone Project

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (3:15 to 3:30)


Descriptions of the capstone projects are here:

https://github.com/MonkmanMH/UVic_BIDA302_capstone




### 6b. Assignment #4

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (3:30 to 3:45)




### 6c. Wrap up

Time allocation: 15 minutes (3:45 to 4:00)

#### Summary

Format: instructor summary, w/ slides


#### Preview/readings for next lesson

Format: instructor summary, w/ slides




-30-
