---
title: "BIDA302: Lesson Plan, Week 5"
subtitle: "2019-11-30"
author: "Martin Monkman"
date: "`r Sys.Date()`"
output: html_document
#description: "The syllabus for Data Analytics Coding Fundamentals, UVic BIDA302"
---

# Week 5 (2019-11-30)

_subject to change_


## Objective

At the end of this lesson, learners will be able to:

1. Demonstrate the ability to work with date values,  

2. Demonstrate the ability to work with text strings, using regular expressions (regex),

3. Use regex in the context of {dplyr} `filter()` and `select()` functions,




***

## Activities

_(revised 2020-03-26; subject to change)_


| Hour  | Block      | Time              | Topics  | &#8212; |
|---    |:---        |:---               |:---:  |
|**1**  |            | **9:00 to 10:00** |    |   |
|       |1a          | 9:00 to 9:30      | Assignment 4: review | &#8212; |
|       |1b          | 9:30 to 10:00     | Modeling (1) | &#8212; |
|**2**  |            | **10:00 to 11:00**| &#8212;  | &#8212; |
|       |&#8212;     | 10:00 to 10:15    | _break_ | &#8212; |
|       |2a          | 10:15 to 11:00    | Modeling (2)  | &#8212; |
|**3**  |            | **11:00 to 12:00**| &#8212;  | &#8212; |
|       |&#8212;     | 11:00 to 11:15    | _break_ | &#8212; |
|       |3a          | 11:15 to 12:00    | Working with dates & times | &#8212; |
|&#8212;|&#8212;     | 12:00 to 1:00     | _lunch_ | &#8212; |
|**4**  |            | **1:00 to 2:00**  | &#8212;  | &#8212; |
|       |4a          | 1:00 to 2:00      | Working with strings | &#8212; |
|**5**  |            | **2:00 to 3:00**  | &#8212;  | &#8212; |
|       |&#8212;     | 2:00 to 2:15      | _break_ | &#8212; |
|       |5a          | 2:15 to 3:00      | Capstone Project: picking your project and getting started | &#8212; |
|**6**  |            | **3:00 to 4:00**  | &#8212;  | &#8212; |
|       |&#8212;     | 3:00 to 3:15      | _break_ | &#8212; |
|       |4a          | 3:15 to 3:30      | Capstone Project: code together | &#8212; |
|       |4c          | 3:45 to 4:00      | Wrap up: the week ahead | &#8212; |



### 1a. Review Homework Assignment #4

Format: participation and instructor lecture w/ slides

Time allocation: 30 minutes (9:00 to 9:30)


### 1b. Introduction to modeling



***

## BREAK

Time allocation: 15 minutes (10:30 to 10:45)

***


### 3. Work with dates and times




Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (11:00 to 11:15)

Format: hands-on exercise

Time allocation: 45 minutes (11:45 to 12:00)

_Reading and resources:_

* _R4DS_, ["Dates and times"](https://r4ds.had.co.nz/dates-and-times.html)

* [Dates and Times Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/lubridate.pdf) (PDF file)

* [{lubridate}](https://lubridate.tidyverse.org/index.html) package reference

* [Working with dates and time in R using the lubridate package](https://data.library.virginia.edu/working-with-dates-and-time-in-r-using-the-lubridate-package/), University of Virginia Library Research Data Services + Sciences



***

## BREAK

Time allocation: 15 minutes (10:30 to 10:45)

***




***

## LUNCH

Time allocation: 60 minutes (12:00 to 1:00)

***

### 3. Working with strings 

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (1:00 to 1:15)

Format: hands-on exercise

Time allocation: 60 minutes (1:15 to 2:15)


_Reading:_

* _R4DS_, ["Strings"](https://r4ds.had.co.nz/strings.html)

* [Work with Strings Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/strings.pdf) (PDF file)

* [regex101.com](https://regex101.com/) -- "regular expression debugger with real time explanation, error detection and highlighting"



***

## BREAK

Time allocation: 15 minutes (2:15 to 2:30)


***

### 4. Capstone Project: picking your project and getting started

Format: participation and instructor lecture w/ slides

Format: hands-on

Time allocation: 90 minutes (10:45 to 12:00)



### 5. Capstone Project: code together

Format: participation and instructor lecture w/ slides

Format: hands-on

Time allocation: 90 minutes (2:30 to 4:00)






-30-
