---
title: "BIDA302: Lesson Plan, Week 1"
subtitle: "2019-11-02"
author: "Martin Monkman"
date: "latest revision: `r Sys.Date()`"
output: html_document
#description: "The syllabus for Data Analytics Coding Fundamentals, UVic BIDA302"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***

**_subject to change_**



## Objectives

> The important thing is that you solve the problem that you’re working on, not write the most concise and elegant code (although that’s definitely something you want to strive towards!)
> - Grolemund & Wickham, _R for Data Science_


At the end of this lesson, learners will be able to:

1. Describe the fundamental elements of good coding practice, and 

2. Demonstrate how these can be applied in a data analytics context.


***

## Activities

| Block      | Time           | Topics  | &#8212; |
|---         |:---            |:---     |:---:  |
|1a          | 9:00 to 9:30   | Welcome to BIDA302!  | &#8212; |
|1b <br> 1c  | 9:30 to 10:30  | Why code? Why R? <br> Introduction to R and RStudio | &#8212; |
|&#8212:     | 10:30 to 10:45 | _break_ | &#8212; |
|2a <br> 2b  | 10:45 to 12:00 | The data science process <br> Data wrangling & Programming foundations | &#8212; |
|&#8212;     | 12:00 to 1:00  | _lunch_ | &#8212; |
|3           | 1:00 to 2:15   | Data wrangling (continued) | &#8212; |
|&#8212;     | 2:15 to 2:30   | _break_ | &#8212; |
|4a          | 2:30 to 3:00   | Assignment 1 | &#8212; |
|4b <br> 4c  | 3:00 to 4:00   | Installing R on your own computer <br> Wrap up | &#8212; |



### 1a. Welcome!

Format: participation and instructor lecture w/ slides

Time allocation: 30 minutes (9:00 to 9:30)


#### Welcome!

* Introducing the instructor

* Value of community 

  - Icebreaker
  


#### What to expect in this class

* read the syllabus!

* course flow

* assignments and evaluation

* Moodle

### 1b. Why Code? Why R?

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (9:00 to 9:45)


### 1c. An introduction to R and RStudio Cloud

Format: learner (instructor guided), using RStudio Cloud

Time allocation: 45 minutes (9:45 to 10:30)

#### RStudio Cloud

* the interface

* simple example

  - R as a calculator
  
  - assignment arrow and objects

* more complex example with {dplyr}

#### R Markdown


## BREAK

Time allocation: 15 minutes (10:30 to 10:45)

***

### 2a. The Data Science Process

Format: instructor, lecture w/slides

Time allocation: 15 minutes (10:45 to 11:00)


### 2b. Data Wrangling

Format: instructor, lecture w/slides

Time allocation: 15 minutes (10:45 to 11:00)



Format: learner (instructor guided)

Time allocation: 60 minutes (11:00 to 12:00)


## LUNCH

Time allocation: 60 minutes (12:00 to 1:00)

***

### 3. Data Wrangling (part 2)

Format: instructor, lecture w/slides

Time allocation: 15 minutes (1:00 to 1:15)


Format: learner (instructor guided)

Time allocation: 60 minutes (1:15 to 2:15)




## BREAK

Time allocation: 15 minutes (2:15 to 2:30)


***

## 4a. Assignment #1

Time allocation: 55 minutes (2:30 to 3:00)


## 4b. Installing R & RStudio on your own computer

Time allocation: 15 minutes (3:15 to 3:30)


## 4c. Wrap up

Time allocation: 30 minutes (3:30 to 4:00)

### Summary

Format: instructor summary, w/ slides

### Questions?

Format: learner Q&A

### Preview/readings for next lesson

Format: instructor summary, w/ slides




***

## Readings 

### From R4DS

Garrett Grolemund and Hadley Wickham, [R for Data Science](https://r4ds.had.co.nz/)

* 


### Digging deeper into this week's topics


Hilary Parker, 2017-08-31, [Opinionated analysis development](https://peerj.com/preprints/3210/), PeerJ Preprints 5:e3210v1 https://doi.org/10.7287/peerj.preprints.3210v1


Nathaniel D. Phillips, [YaRrr! The Pirate’s Guide to R](https://bookdown.org/ndphillips/YaRrr/) 

- [Chapter 1.3, "Why is R so great?"](https://bookdown.org/ndphillips/YaRrr/why-is-r-so-great.html)

- [Chapter 2, "Getting Started"](https://bookdown.org/ndphillips/YaRrr/started.html) provides a good summary of R, RStudio, and packages

"History and Overview of R", Chapter 2 in Roger Peng, 2019-12-22, [_R Programming for Data Science_](https://bookdown.org/rdpeng/rprogdatascience/history-and-overview-of-r.html)

Lucy D'Agostino McGowan, 2017-07-28, [R release names](https://livefreeordichotomize.com/2017/09/28/r-release-names/)

- [an up-to-date list](https://bookdown.org/martin_monkman/DataScienceResources_book/using-r.html#r-release-names)



### Getting ready for next week

The BIDA302 Course Syllabus.

Hadley Wickham. ["Tidy data"](https://vita.had.co.nz/papers/tidy-data.html), _The Journal of Statistical Software_, vol. 59, 2014.

Karl Broman and Kara Woo, ["Data organization in spreadsheets"](https://doi.org/10.1080/00031305.2017.1375989), _The American Statistician_ 72 (1): 2–10.

[Data Organization in Spreadsheets for Social Scientists: Formatting problems](https://datacarpentry.org/spreadsheets-socialsci/02-common-mistakes/index.html) -- DataCarpentry lesson




-30-
