---
title: "BIDA302: Lesson Plan, Week 5"
subtitle: "2019-11-30"
author: "Martin Monkman"
date: "`r Sys.Date()`"
output: html_document
#description: "The syllabus for Data Analytics Coding Fundamentals, UVic BIDA302"
---

# Week 5 (2019-11-30)

_subject to change_


## Objective

At the end of this lesson, learners will be able to:

1. Demonstrate the ability to work with date values,  

2. Demonstrate the ability to work with text strings, using regular expressions (regex),

3. Use regex in the context of {dplyr} `filter()` and `select()` functions,

4. Explain the use of statistical models in data analysis, and demonstrate the script to build a simple model



***

## Activities

_(subject to change)_

| Block      | Time           | Topics  | &#8212; |
|---         |:---            |:---     |:---:  |
|1a          | 9:00 to 9:30   | Review Homework Exercise #3 | &#8212; |
|1b          | 9:30 to 10:30  | Working with strings (1) | &#8212; |
|&#8212:     | 10:30 to 10:45 | _break_ | &#8212; |
|2           | 10:45 to 12:00 | Introduction to models | &#8212; |
|&#8212;     | 12:00 to 1:00  | _lunch_ | &#8212; |
|3           | 1:00 to 2:15   | Working with dates | &#8212; |
|&#8212;     | 2:15 to 2:30   | _break_ | &#8212; |
|4           | 2:30 to 4:00   | Capstone Project | &#8212; |



### 1a. Review Homework Exercise #3

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (9:30 to 9:45)

### 1b. Working with strings 

Format: hands-on exercise

Time allocation: 45 minutes (9:45 to 10:30)


_Reading:_

* _R4DS_, ["Strings"](https://r4ds.had.co.nz/strings.html)

* [Work with Strings Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/strings.pdf) (PDF file)

* [regex101.com](https://regex101.com/) -- "regular expression debugger with real time explanation, error detection and highlighting"



***

## BREAK

Time allocation: 15 minutes (10:30 to 10:45)

***


### 2. Introduction to modeling

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (10:45 to 11:00)

Format: hands-on exercise

Time allocation: 60 minutes (11:00 to 12:00)

_Reading:_

* _R4DS_, section IV Model:

  - ["Model - Introduction"](https://r4ds.had.co.nz/model-intro.html) 
  - ["Model Basics"](https://r4ds.had.co.nz/model-basics.html), and 
  - ["Model building"](https://r4ds.had.co.nz/model-building.html)




***

## LUNCH

Time allocation: 60 minutes (12:00 to 1:00)

***


### 3. Work with dates

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (1:00 to 1:15)

Format: hands-on exercise

Time allocation: 60 minutes (1:15 to 2:15)

_Reading:_

* _R4DS_, ["Dates and times"](https://r4ds.had.co.nz/dates-and-times.html)

* [Dates and Times Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/lubridate.pdf) (PDF file)


***

## BREAK

Time allocation: 15 minutes (2:15 to 2:30)


***


### 4. Capstone Project

Format: participation and instructor lecture w/ slides

Time allocation: 90 minutes (2:30 to 4:00)







-30-
