---
title: "hexSticker - fontface test"
output: html_notebook
---

## `load_all()`

```{r}

devtools::load_all()

```



as shown on hexSticker readme
https://github.com/GuangchuangYu/hexSticker

```{r}

teststicker <- 
sticker(expression(plot(cars, cex=.5, cex.axis=.5, mgp=c(0,.3,0), xlab="", ylab="")),
        package="hexSticker", p_size=8, s_x=1, s_y=.8, s_width=1.2, s_height=1)

teststicker

```


with google font "Roboto"

uses {showtext}
https://github.com/yixuan/showtext

```{r}

library(showtext)
## Loading Google fonts (http://www.google.com/fonts)
font_add_google("Roboto", "roboto")


teststicker <- 
sticker(expression(plot(cars, cex=.5, cex.axis=.5, mgp=c(0,.3,0), xlab="", ylab="")),
        package="hexSticker", p_size=8, s_x=1, s_y=.8, s_width=1.2, s_height=1,
        p_family = "roboto")

teststicker

```



with google font "Roboto" and fontface "italic"

```{r}


teststicker <- 
sticker(expression(plot(cars, cex=.5, cex.axis=.5, mgp=c(0,.3,0), xlab="", ylab="")),
        package="hexSticker", p_size=8, s_x=1, s_y=.8, s_width=1.2, s_height=1,
        p_family = "roboto", p_face = "italic")

teststicker

```

