---
title: "Rolling Stone 500 - sales data"
output: html_notebook
---

This script uses the [_Rolling Stone's_ 500 Greatest Albums of All Time](https://en.wikipedia.org/wiki/Rolling_Stone%27s_500_Greatest_Albums_of_All_Time) (2012 version) to generate a fake sales order.

Data source is 

* https://data.world/notgibs/rolling-stones-top-500-albums

* download link https://query.data.world/s/sc4hbemuc4htolfcah7fs7l2oukegq


```{r setup}

library(tidyverse)

library(glue)

```


## Read data

```{r}

albumlist <- read_csv("albumlist.csv")

albumlist

albumlist50 <- albumlist %>%
  filter(Number < 51)

```

## Generate customer (store) ID table

Note: store list is defunct record retailers from [Wikipedia List of defunct Canadian companies](https://en.wikipedia.org/wiki/List_of_defunct_Canadian_companies#Consumer_retail,_including_grocery)


```{r}

storelist <- c("A&A", "A&B", "HMV", "Kelly's", "Sam The Record Man")
regionlist <- c("north", "east", "south", "west")

ndf = 10

customerlist <- data.frame(
  customer.id = 100:(ndf+99),
  store = sample(storelist, ndf, replace = TRUE),
  region = sample(regionlist, ndf, replace = TRUE, prob = c(0.4, 0.3, 0.2, 0.1))
  )

customerlist <-
customerlist %>%
  mutate(customer.id = as.character(glue('X{customer.id}')))

customerlist

```

## Create order

### album_order_fun

```{r}

album_order_fun <- function(...){
  sample_n(albumlist50, 1) %>%
    select(Artist, Album) %>%
  mutate(format = sample(c("lp", "cass"), 1, prob = c(0.33, 0.67)),
         qty = rpois(1, 4))
}


# TEST
album_order_fun()


```


### multiples

```{r}
# TEST

n = rpois(1, 7)
order_final <- data.frame(Artist = as.character(),
                          Album = as.character(),
                          format = as.character(),
                          qty = as.integer(),
                          stringsAsFactors = FALSE)  
#ls.str(order_final)
#rbind(order_final, order_fun())
#
for(i in 1:n){
  order_final[i, ] <- album_order_fun()
}

order_final

```



```{r}

order_fun <- function(){
  n = rpois(1, 7)
  order_final <- data.frame(Artist = as.character(),
                          Album = as.character(),
                          format = as.character(),
                          qty = as.integer(),
                          stringsAsFactors = FALSE)  
  
  for(i in 1:n){
    order_final[i, ] <- album_order_fun()
  }
  order_final
  }


```


```{r}

order_fun()


```


