---
title: "BIDA302: Lesson Plan, Week 4"
subtitle: ""
author: "Martin Monkman"
date: "update: `r Sys.Date()`"
output: html_document
#description: "The syllabus for Data Analytics Coding Fundamentals, UVic BIDA302"
---

# Week 4 


## Objective

At the end of this lesson, learners will be able to:

1. Demonstrate their ability to write a simple function in R.

2. Have a foundational understanding of modeling in R.



***

## Activities

_(subject to change)_

| Hour  | Block      | Time              | Topics  | &#8212; |
|---    |:---        |:---               |:---:  |
|**Saturday**     | &#8212;  | &#8212; | &#8212; |
|**1**  |            | **9:00 to 10:00**| &#8212;  | &#8212; |
|       |1a          | 9:00 to 9:30      | Review Homework Exercise #3  <BR> | &#8212; |
|       |1b          | 9:30 to 10:00     | Course: mid-point review | &#8212; |
|**2**  |            | **10:00 to 11:00**| &#8212;  | &#8212; |
|       |&#8212;     | 10:00 to 10:15    | _break_ | &#8212; |
|       |2a          | 10:15 to 11:00    | Writing your own functions (1) | &#8212; |
|**3**  |            | **11:00 to 12:00**| &#8212;  | &#8212; |
|       |&#8212;     | 11:00 to 11:15    | _break_ | &#8212; |
|       |3a          | 11:15 to 11:45    | Writing your own functions (2) | &#8212; |
|       |3b          | 11:45 to 12:00    | Questions? Comments? <br> Wrap up | &#8212; |
|**Sunday**     | &#8212;  | &#8212; | &#8212; |
|**4**  |            | **9:00 to 10:00**| &#8212;  | &#8212; |
|       |4a          | 9:00 to 9:30      | Discussion: "Data Organization in Spreadsheets"  | &#8212; |
|       |4b          | 9:30 to 10:00     | Introduction to modeling (1) | &#8212; |
|**5**  |            | **10:00 to 11:00**| _break_  | &#8212; |
|       |5a          | 10:15 to 11:00    | Introduction to modeling (2) | &#8212; |
|**6**  |            | **11:00 to 12:00**| &#8212;  | &#8212; |
|       |&#8212;     | 11:00 to 11:15    | _break_ | &#8212; |
|       |6a          | 11:15 to 11:45    | Assignment 4 | &#8212; |
|       |6b          | 11:45 to 12:00    | Questions? Comments? <br> Wrap up | &#8212; |


***


## SATURDAY

### 1a. Review Homework Exercise #3 - data importing and plotting

Format: instructor demonstration and participation 

Time allocation: 30 minutes (9:00 to 9:30)



### 1b. Course: mid-point review

Format: instructor lecture w/ slides

Time allocation: 30 minutes (9:30 to 10:00)




***

## BREAK

Time allocation: 15 minutes (10:00 to 10:15)

***


### 2a. Writing your own functions (1)

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (10:15 to 10:30)

Format: hands-on exercise

Time allocation: 30 minutes (10:30 to 11:00)



***

## BREAK

Time allocation: 15 minutes (11:00 to 11:15)

***


### 3a. Writing your own functions (2)

Format: hands-on exercise

Time allocation: 30 minutes (11:15 to 11:45)




### 3b. Reading / Questions? Comments

Format: participation

Time allocation: 15 minutes (11:45 to 12:00




***

## SUNDAY



### 4a. Discussion

Format: breakout rooms

Time allocation: 30 minutes (9:00 to 9:15)


Reading: 

Karl W. Broman and Kara H. Woo, "Data Organization in Spreadsheets", _The American Statistician_, Vol 72, Issue 1: Special Issue on Data Science, 2018

* https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989


Discussion questions:

* How many people have used spreadsheets, in their research, courses, or at home?

* How many people have accidentally done something that made them frustrated or sad?

* What are basic principles for using spreadsheets for good data organization?

* What are good approaches for handling dates in spreadsheets?



### 4b. Introduction to modeling (1) 

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (9:15 to 9:30)

Format: hands-on exercise

Time allocation: 30 minutes (9:30 to 10:00)



***

## BREAK

Time allocation: 15 minutes (10:00 to 10:15)

***




### 5. Introduction to modeling (2) 



Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (10:15 to 10:30)

Format: hands-on exercise

Time allocation: 30 minutes (10:30 to 11:00)






***

## BREAK

Time allocation: 15 minutes (11:00 to 11:15)


***




### 6a. Assignment #4 

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (11:15 to 11:45)



### 6b. Wrap up

Time allocation: 15 minutes (11:45 to 12:00)


#### Preview/readings for next lesson

Format: instructor summary, w/ slides



## Readings & Reference Materials


Karl W. Broman and Kara H. Woo, "Data Organization in Spreadsheets", _The American Statistician_, Vol 72, Issue 1: Special Issue on Data Science

* https://www.tandfonline.com/doi/full/10.1080/00031305.2017.1375989


### Readings from _R4DS_

Garrett Grolemund and Hadley Wickham, [R for Data Science](https://r4ds.had.co.nz/)

* [19. Functions](https://r4ds.had.co.nz/functions.html)

* [Model: 22. Introduction and 23. Model Basics](https://r4ds.had.co.nz/model-intro.html)


## Capstone projects

Some resources:

[_Maclean's_: Charts to watch in 2021: The most important Canadian economic graphs for the year ahead](https://www.macleans.ca/economy/charts-to-watch-in-2021-the-most-important-canadian-economic-charts-for-the-year-ahead/)


[_Maclean's_: The most important Canadian economic charts to watch in 2020](https://www.macleans.ca/economy/the-most-important-canadian-economic-charts-to-watch-in-2020/) (2019-12-04)

[_Maclean's_: The most important charts to watch in 2019](https://www.macleans.ca/economy/economicanalysis/the-most-important-charts-to-watch-in-2019/)

* Alberta Recovery

-30-
